//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string ActionsColumn {
            get {
                return ResourceManager.GetString("ActionsColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new car.
        /// </summary>
        public static string AddNewCar {
            get {
                return ResourceManager.GetString("AddNewCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new district here.
        /// </summary>
        public static string addNewDistrict {
            get {
                return ResourceManager.GetString("addNewDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new user.
        /// </summary>
        public static string AddNewUser {
            get {
                return ResourceManager.GetString("AddNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string addString {
            get {
                return ResourceManager.GetString("addString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add your car info here!.
        /// </summary>
        public static string AddYourCarInfoHere {
            get {
                return ResourceManager.GetString("AddYourCarInfoHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        public static string Administrator {
            get {
                return ResourceManager.GetString("Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awaiting order.
        /// </summary>
        public static string AwaitingOrder {
            get {
                return ResourceManager.GetString("AwaitingOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string cancelButton {
            get {
                return ResourceManager.GetString("cancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Class.
        /// </summary>
        public static string CarClass {
            get {
                return ResourceManager.GetString("CarClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Econom class.
        /// </summary>
        public static string CarClassEconom {
            get {
                return ResourceManager.GetString("CarClassEconom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Class.
        /// </summary>
        public static string CarClassError {
            get {
                return ResourceManager.GetString("CarClassError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General class.
        /// </summary>
        public static string CarClassGeneral {
            get {
                return ResourceManager.GetString("CarClassGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premium class.
        /// </summary>
        public static string CarClassPremium {
            get {
                return ResourceManager.GetString("CarClassPremium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autopark.
        /// </summary>
        public static string CarEditor {
            get {
                return ResourceManager.GetString("CarEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car manufacture Date.
        /// </summary>
        public static string CarManufactureDate {
            get {
                return ResourceManager.GetString("CarManufactureDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Date.
        /// </summary>
        public static string CarMDError {
            get {
                return ResourceManager.GetString("CarMDError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Name.
        /// </summary>
        public static string CarName {
            get {
                return ResourceManager.GetString("CarName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Name.
        /// </summary>
        public static string CarNameError {
            get {
                return ResourceManager.GetString("CarNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name must be less than 50 symbols.
        /// </summary>
        public static string CarNameErrorMessage {
            get {
                return ResourceManager.GetString("CarNameErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Nick Name.
        /// </summary>
        public static string CarNickName {
            get {
                return ResourceManager.GetString("CarNickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid NickName.
        /// </summary>
        public static string CarNickNameError {
            get {
                return ResourceManager.GetString("CarNickNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Number.
        /// </summary>
        public static string CarNumber {
            get {
                return ResourceManager.GetString("CarNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Number.
        /// </summary>
        public static string CarNumberError {
            get {
                return ResourceManager.GetString("CarNumberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Occupation.
        /// </summary>
        public static string CarOccupation {
            get {
                return ResourceManager.GetString("CarOccupation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Number.
        /// </summary>
        public static string CarOccupError {
            get {
                return ResourceManager.GetString("CarOccupError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Petrol consumption.
        /// </summary>
        public static string CarPCError {
            get {
                return ResourceManager.GetString("CarPCError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Petrol Consumption.
        /// </summary>
        public static string CarPetrolConsumption {
            get {
                return ResourceManager.GetString("CarPetrolConsumption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diesel.
        /// </summary>
        public static string CarPetrolDiesel {
            get {
                return ResourceManager.GetString("CarPetrolDiesel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal-80.
        /// </summary>
        public static string CarPetrolNormal {
            get {
                return ResourceManager.GetString("CarPetrolNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string CarPetrolOther {
            get {
                return ResourceManager.GetString("CarPetrolOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premium-95.
        /// </summary>
        public static string CarPetrolPremium {
            get {
                return ResourceManager.GetString("CarPetrolPremium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular-92.
        /// </summary>
        public static string CarPetrolRegular {
            get {
                return ResourceManager.GetString("CarPetrolRegular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super-98.
        /// </summary>
        public static string CarPetrolSuper {
            get {
                return ResourceManager.GetString("CarPetrolSuper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Petrol Type.
        /// </summary>
        public static string CarPetrolType {
            get {
                return ResourceManager.GetString("CarPetrolType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Petrol type.
        /// </summary>
        public static string CarPetrolTypeError {
            get {
                return ResourceManager.GetString("CarPetrolTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car registration.
        /// </summary>
        public static string CarRegistration {
            get {
                return ResourceManager.GetString("CarRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string CarResetBtn {
            get {
                return ResourceManager.GetString("CarResetBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string CarSaveBtn {
            get {
                return ResourceManager.GetString("CarSaveBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete info.
        /// </summary>
        public static string CarsDeleteInfo {
            get {
                return ResourceManager.GetString("CarsDeleteInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string CarsDetails {
            get {
                return ResourceManager.GetString("CarsDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car State.
        /// </summary>
        public static string CarState {
            get {
                return ResourceManager.GetString("CarState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid State.
        /// </summary>
        public static string CarStateError {
            get {
                return ResourceManager.GetString("CarStateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On repair.
        /// </summary>
        public static string CarStateRepairing {
            get {
                return ResourceManager.GetString("CarStateRepairing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working.
        /// </summary>
        public static string CarStateWorking {
            get {
                return ResourceManager.GetString("CarStateWorking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car status.
        /// </summary>
        public static string CarStatus {
            get {
                return ResourceManager.GetString("CarStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change status for current car?.
        /// </summary>
        public static string CarStatusConfirmation {
            get {
                return ResourceManager.GetString("CarStatusConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status change confirmation.
        /// </summary>
        public static string CarStatusConfirmHeader {
            get {
                return ResourceManager.GetString("CarStatusConfirmHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string CarStatusMain {
            get {
                return ResourceManager.GetString("CarStatusMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spare.
        /// </summary>
        public static string CarStatusSpare {
            get {
                return ResourceManager.GetString("CarStatusSpare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string CarToMenuBtn {
            get {
                return ResourceManager.GetString("CarToMenuBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change driver.
        /// </summary>
        public static string ChangeDriver {
            get {
                return ResourceManager.GetString("ChangeDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change menu.
        /// </summary>
        public static string ChangeMenu {
            get {
                return ResourceManager.GetString("ChangeMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string ChangeOwner {
            get {
                return ResourceManager.GetString("ChangeOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string ChangeString {
            get {
                return ResourceManager.GetString("ChangeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City districts.
        /// </summary>
        public static string Citydistricts {
            get {
                return ResourceManager.GetString("Citydistricts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        public static string Client {
            get {
                return ResourceManager.GetString("Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive History.
        /// </summary>
        public static string ClientDriveHistory {
            get {
                return ResourceManager.GetString("ClientDriveHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Service.
        /// </summary>
        public static string ClientService {
            get {
                return ResourceManager.GetString("ClientService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this address?.
        /// </summary>
        public static string ConfirmDeletingAddress {
            get {
                return ResourceManager.GetString("ConfirmDeletingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Information.
        /// </summary>
        public static string ContactInformation {
            get {
                return ResourceManager.GetString("ContactInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter all required information into the form below..
        /// </summary>
        public static string CreateAttention1 {
            get {
                return ResourceManager.GetString("CreateAttention1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to add all information correctly..
        /// </summary>
        public static string CreateAttention2 {
            get {
                return ResourceManager.GetString("CreateAttention2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here is car registration page.
        /// </summary>
        public static string CreateHeader1 {
            get {
                return ResourceManager.GetString("CreateHeader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep in mind.
        /// </summary>
        public static string CreateHeader2 {
            get {
                return ResourceManager.GetString("CreateHeader2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We still don&apos;t know where You are. Please choose district of Your location..
        /// </summary>
        public static string CreateLocation {
            get {
                return ResourceManager.GetString("CreateLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new address.
        /// </summary>
        public static string CreateNewAddressString {
            get {
                return ResourceManager.GetString("CreateNewAddressString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chernivtsi.
        /// </summary>
        public static string DefaultValueOfCity {
            get {
                return ResourceManager.GetString("DefaultValueOfCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are attempting to delete all information about selected car. Deleted information will be lost..
        /// </summary>
        public static string DeleteAttention1 {
            get {
                return ResourceManager.GetString("DeleteAttention1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Confirmation.
        /// </summary>
        public static string deleteConfirm {
            get {
                return ResourceManager.GetString("deleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted districts list.
        /// </summary>
        public static string DeletedDistricts {
            get {
                return ResourceManager.GetString("DeletedDistricts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete this entry?.
        /// </summary>
        public static string deleteDstEntryQuestion {
            get {
                return ResourceManager.GetString("deleteDstEntryQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention!.
        /// </summary>
        public static string DeleteHeader1 {
            get {
                return ResourceManager.GetString("DeleteHeader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string deleteString {
            get {
                return ResourceManager.GetString("deleteString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can view all your car info here..
        /// </summary>
        public static string DetailsAttention1 {
            get {
                return ResourceManager.GetString("DetailsAttention1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here is car details page.
        /// </summary>
        public static string DetailsHeader1 {
            get {
                return ResourceManager.GetString("DetailsHeader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string detailsString {
            get {
                return ResourceManager.GetString("detailsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District.
        /// </summary>
        public static string District {
            get {
                return ResourceManager.GetString("District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basket.
        /// </summary>
        public static string DistrictBasket {
            get {
                return ResourceManager.GetString("DistrictBasket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District editor.
        /// </summary>
        public static string DistrictEditor {
            get {
                return ResourceManager.GetString("DistrictEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District name.
        /// </summary>
        public static string DistrictName {
            get {
                return ResourceManager.GetString("DistrictName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can find information about other drivers currently working.
        ///					To start workingshift please press &quot;Start Shift&quot; button.
        /// </summary>
        public static string DistrictPartAttention1 {
            get {
                return ResourceManager.GetString("DistrictPartAttention1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not forget to end your working shift by pressing &quot;End Shift&quot; button.
        /// </summary>
        public static string DistrictPartAttention2 {
            get {
                return ResourceManager.GetString("DistrictPartAttention2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is your working place.
        /// </summary>
        public static string DistrictPartHeader1 {
            get {
                return ResourceManager.GetString("DistrictPartHeader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep in mind.
        /// </summary>
        public static string DistrictPartHeader2 {
            get {
                return ResourceManager.GetString("DistrictPartHeader2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Districts.
        /// </summary>
        public static string Districts {
            get {
                return ResourceManager.GetString("Districts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doing order.
        /// </summary>
        public static string DoingOrder {
            get {
                return ResourceManager.GetString("DoingOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive.
        /// </summary>
        public static string Drive {
            get {
                return ResourceManager.GetString("Drive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver.
        /// </summary>
        public static string Driver {
            get {
                return ResourceManager.GetString("Driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are here.
        /// </summary>
        public static string DriverIsHere {
            get {
                return ResourceManager.GetString("DriverIsHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drivers activity.
        /// </summary>
        public static string DriversActivity {
            get {
                return ResourceManager.GetString("DriversActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop place.
        /// </summary>
        public static string DropPlace {
            get {
                return ResourceManager.GetString("DropPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter all required information into the form below..
        /// </summary>
        public static string EditAttention1 {
            get {
                return ResourceManager.GetString("EditAttention1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit or delete your information wisely!.
        /// </summary>
        public static string EditAttention2 {
            get {
                return ResourceManager.GetString("EditAttention2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here is car registration page.
        /// </summary>
        public static string EditHeader1 {
            get {
                return ResourceManager.GetString("EditHeader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Be carefull.
        /// </summary>
        public static string EditHeader2 {
            get {
                return ResourceManager.GetString("EditHeader2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If You like to change Your location,  please choose district from the list..
        /// </summary>
        public static string EditLocation {
            get {
                return ResourceManager.GetString("EditLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string editString {
            get {
                return ResourceManager.GetString("editString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit car info.
        /// </summary>
        public static string EditYourCar {
            get {
                return ResourceManager.GetString("EditYourCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is empty.
        /// </summary>
        public static string EmptyEmail {
            get {
                return ResourceManager.GetString("EmptyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is empty.
        /// </summary>
        public static string EmptyPassword {
            get {
                return ResourceManager.GetString("EmptyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName is empty.
        /// </summary>
        public static string EmptyUserName {
            get {
                return ResourceManager.GetString("EmptyUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new district name:.
        /// </summary>
        public static string enterDistrictName {
            get {
                return ResourceManager.GetString("enterDistrictName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new district name.
        /// </summary>
        public static string enterNewDstName {
            get {
                return ResourceManager.GetString("enterNewDstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your address.
        /// </summary>
        public static string EnterYourAdress {
            get {
                return ResourceManager.GetString("EnterYourAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your garage.
        /// </summary>
        public static string Garage {
            get {
                return ResourceManager.GetString("Garage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All information about your car or cars will be displayed here. You can always view, add, edit or delete each car you want..
        /// </summary>
        public static string GarageAttention1 {
            get {
                return ResourceManager.GetString("GarageAttention1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always keep your information up to date. Do not forget to update information you submited..
        /// </summary>
        public static string GarageAttention2 {
            get {
                return ResourceManager.GetString("GarageAttention2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is your virtual garage.
        /// </summary>
        public static string GarageHeader1 {
            get {
                return ResourceManager.GetString("GarageHeader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep in mind.
        /// </summary>
        public static string GarageHeader2 {
            get {
                return ResourceManager.GetString("GarageHeader2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give this car to a new owner?.
        /// </summary>
        public static string GiveCarEntry {
            get {
                return ResourceManager.GetString("GiveCarEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome home.
        /// </summary>
        public static string Greeting {
            get {
                return ResourceManager.GetString("Greeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has order.
        /// </summary>
        public static string HasOrder {
            get {
                return ResourceManager.GetString("HasOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is intersity.
        /// </summary>
        public static string IsIntercity {
            get {
                return ResourceManager.GetString("IsIntercity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is standart.
        /// </summary>
        public static string IsStandart {
            get {
                return ResourceManager.GetString("IsStandart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join.
        /// </summary>
        public static string Join {
            get {
                return ResourceManager.GetString("Join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last update.
        /// </summary>
        public static string LastUpdate {
            get {
                return ResourceManager.GetString("LastUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName or Email is already exists.
        /// </summary>
        public static string LoginEmailExist {
            get {
                return ResourceManager.GetString("LoginEmailExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To main menu.
        /// </summary>
        public static string MainLink {
            get {
                return ResourceManager.GetString("MainLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle name.
        /// </summary>
        public static string MiddleName {
            get {
                return ResourceManager.GetString("MiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimal price.
        /// </summary>
        public static string MinimalPrice {
            get {
                return ResourceManager.GetString("MinimalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New owner.
        /// </summary>
        public static string newCarOwner {
            get {
                return ResourceManager.GetString("newCarOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No status.
        /// </summary>
        public static string NoStatus {
            get {
                return ResourceManager.GetString("NoStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string NumberHouse {
            get {
                return ResourceManager.GetString("NumberHouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One minute cost.
        /// </summary>
        public static string OneMinuteCost {
            get {
                return ResourceManager.GetString("OneMinuteCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator.
        /// </summary>
        public static string Operator {
            get {
                return ResourceManager.GetString("Operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Taxi.
        /// </summary>
        public static string OrderTaxi {
            get {
                return ResourceManager.GetString("OrderTaxi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peec place.
        /// </summary>
        public static string PeekPlace {
            get {
                return ResourceManager.GetString("PeekPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal cabinet.
        /// </summary>
        public static string PersonalCabinet {
            get {
                return ResourceManager.GetString("PersonalCabinet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReportViewer.
        /// </summary>
        public static string ReportViewer {
            get {
                return ResourceManager.GetString("ReportViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current field is empty. Please fill it..
        /// </summary>
        public static string RequiredError {
            get {
                return ResourceManager.GetString("RequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resting.
        /// </summary>
        public static string Resting {
            get {
                return ResourceManager.GetString("Resting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string RestoreDistrict {
            get {
                return ResourceManager.GetString("RestoreDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        public static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return this car to it`s owner?.
        /// </summary>
        public static string ReturnCarEntry {
            get {
                return ResourceManager.GetString("ReturnCarEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run time.
        /// </summary>
        public static string Runtime {
            get {
                return ResourceManager.GetString("Runtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string saveButton {
            get {
                return ResourceManager.GetString("saveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Tarif.
        /// </summary>
        public static string SelectTarif {
            get {
                return ResourceManager.GetString("SelectTarif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        public static string Set {
            get {
                return ResourceManager.GetString("Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set date.
        /// </summary>
        public static string Setdate {
            get {
                return ResourceManager.GetString("Setdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set VIP Status.
        /// </summary>
        public static string SetVIPStatusPage {
            get {
                return ResourceManager.GetString("SetVIPStatusPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is less than 5 characters.
        /// </summary>
        public static string ShortPassword {
            get {
                return ResourceManager.GetString("ShortPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName is less than 4 characters.
        /// </summary>
        public static string ShortUserName {
            get {
                return ResourceManager.GetString("ShortUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sing Up.
        /// </summary>
        public static string SingUp {
            get {
                return ResourceManager.GetString("SingUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start price.
        /// </summary>
        public static string StartPrice {
            get {
                return ResourceManager.GetString("StartPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        public static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarifes.
        /// </summary>
        public static string Tarifes {
            get {
                return ResourceManager.GetString("Tarifes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new address.
        /// </summary>
        public static string TitleCreateAddress {
            get {
                return ResourceManager.GetString("TitleCreateAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Your location.
        /// </summary>
        public static string TitleCreateLocation {
            get {
                return ResourceManager.GetString("TitleCreateLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete current address.
        /// </summary>
        public static string TitleDeleteAddress {
            get {
                return ResourceManager.GetString("TitleDeleteAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit current address.
        /// </summary>
        public static string TitleEditAddress {
            get {
                return ResourceManager.GetString("TitleEditAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Your location.
        /// </summary>
        public static string TitleEditLocation {
            get {
                return ResourceManager.GetString("TitleEditLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourite addresses.
        /// </summary>
        public static string TitleLeftMenuUserAddress {
            get {
                return ResourceManager.GetString("TitleLeftMenuUserAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your favourite addresses.
        /// </summary>
        public static string TitleMainMenuAddress {
            get {
                return ResourceManager.GetString("TitleMainMenuAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string TitleMainMenuLocation {
            get {
                return ResourceManager.GetString("TitleMainMenuLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update profile.
        /// </summary>
        public static string UpdateProfile {
            get {
                return ResourceManager.GetString("UpdateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Id.
        /// </summary>
        public static string UserId {
            get {
                return ResourceManager.GetString("UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User list.
        /// </summary>
        public static string UserMenu {
            get {
                return ResourceManager.GetString("UserMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User page.
        /// </summary>
        public static string UserPage {
            get {
                return ResourceManager.GetString("UserPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting cost.
        /// </summary>
        public static string WaitingCost {
            get {
                return ResourceManager.GetString("WaitingCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workshift.
        /// </summary>
        public static string WorkShift {
            get {
                return ResourceManager.GetString("WorkShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Shift.
        /// </summary>
        public static string WorkShiftEnd {
            get {
                return ResourceManager.GetString("WorkShiftEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Shift.
        /// </summary>
        public static string WorkShiftStart {
            get {
                return ResourceManager.GetString("WorkShiftStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift started.
        /// </summary>
        public static string WorkStarted {
            get {
                return ResourceManager.GetString("WorkStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are in:.
        /// </summary>
        public static string YourCurrentLocation {
            get {
                return ResourceManager.GetString("YourCurrentLocation", resourceCulture);
            }
        }
    }
}
