//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Actions.
        /// </summary>
        public static string ActionsColumn {
            get {
                return ResourceManager.GetString("ActionsColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add new car.
        /// </summary>
        public static string AddNewCar {
            get {
                return ResourceManager.GetString("AddNewCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add new district here.
        /// </summary>
        public static string addNewDistrict {
            get {
                return ResourceManager.GetString("addNewDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add new user.
        /// </summary>
        public static string AddNewUser {
            get {
                return ResourceManager.GetString("AddNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add.
        /// </summary>
        public static string addString {
            get {
                return ResourceManager.GetString("addString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add your car info here!.
        /// </summary>
        public static string AddYourCarInfoHere {
            get {
                return ResourceManager.GetString("AddYourCarInfoHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Administrator.
        /// </summary>
        public static string Administrator {
            get {
                return ResourceManager.GetString("Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Are you sure?.
        /// </summary>
        public static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Awaiting order.
        /// </summary>
        public static string AwaitingOrder {
            get {
                return ResourceManager.GetString("AwaitingOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string cancelButton {
            get {
                return ResourceManager.GetString("cancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Car Class.
        /// </summary>
        public static string CarClass {
            get {
                return ResourceManager.GetString("CarClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Econom class.
        /// </summary>
        public static string CarClassEconom {
            get {
                return ResourceManager.GetString("CarClassEconom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid Class.
        /// </summary>
        public static string CarClassError {
            get {
                return ResourceManager.GetString("CarClassError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на General class.
        /// </summary>
        public static string CarClassGeneral {
            get {
                return ResourceManager.GetString("CarClassGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Premium class.
        /// </summary>
        public static string CarClassPremium {
            get {
                return ResourceManager.GetString("CarClassPremium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Autopark.
        /// </summary>
        public static string CarEditor {
            get {
                return ResourceManager.GetString("CarEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Car manufacture Date.
        /// </summary>
        public static string CarManufactureDate {
            get {
                return ResourceManager.GetString("CarManufactureDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid Date.
        /// </summary>
        public static string CarMDError {
            get {
                return ResourceManager.GetString("CarMDError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Car Name.
        /// </summary>
        public static string CarName {
            get {
                return ResourceManager.GetString("CarName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid Name. Name must be less than 30 and more than 2 symbols.
        /// </summary>
        public static string CarNameError {
            get {
                return ResourceManager.GetString("CarNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name must be less than 30 and more than 2 symbols.
        /// </summary>
        public static string CarNameErrorMessage {
            get {
                return ResourceManager.GetString("CarNameErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Car Nick Name.
        /// </summary>
        public static string CarNickName {
            get {
                return ResourceManager.GetString("CarNickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid NickName. Must contain more than 1 and up to 4 digits only.
        /// </summary>
        public static string CarNickNameError {
            get {
                return ResourceManager.GetString("CarNickNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You haven`t choose a main car..
        /// </summary>
        public static string CarNotFoundError {
            get {
                return ResourceManager.GetString("CarNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Car Number.
        /// </summary>
        public static string CarNumber {
            get {
                return ResourceManager.GetString("CarNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid Number. Must match CC0000CC pattern..
        /// </summary>
        public static string CarNumberError {
            get {
                return ResourceManager.GetString("CarNumberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Car Occupation.
        /// </summary>
        public static string CarOccupation {
            get {
                return ResourceManager.GetString("CarOccupation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid Number. Must be more than 1 and less than 20..
        /// </summary>
        public static string CarOccupError {
            get {
                return ResourceManager.GetString("CarOccupError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid Petrol consumption. Must be more than 0 and less than 100..
        /// </summary>
        public static string CarPCError {
            get {
                return ResourceManager.GetString("CarPCError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Car Petrol Consumption (l/100km).
        /// </summary>
        public static string CarPetrolConsumption {
            get {
                return ResourceManager.GetString("CarPetrolConsumption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Diesel.
        /// </summary>
        public static string CarPetrolDiesel {
            get {
                return ResourceManager.GetString("CarPetrolDiesel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Normal-80.
        /// </summary>
        public static string CarPetrolNormal {
            get {
                return ResourceManager.GetString("CarPetrolNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Other.
        /// </summary>
        public static string CarPetrolOther {
            get {
                return ResourceManager.GetString("CarPetrolOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Premium-95.
        /// </summary>
        public static string CarPetrolPremium {
            get {
                return ResourceManager.GetString("CarPetrolPremium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Regular-92.
        /// </summary>
        public static string CarPetrolRegular {
            get {
                return ResourceManager.GetString("CarPetrolRegular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Super-98.
        /// </summary>
        public static string CarPetrolSuper {
            get {
                return ResourceManager.GetString("CarPetrolSuper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Petrol Type.
        /// </summary>
        public static string CarPetrolType {
            get {
                return ResourceManager.GetString("CarPetrolType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid Petrol type.
        /// </summary>
        public static string CarPetrolTypeError {
            get {
                return ResourceManager.GetString("CarPetrolTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Car registration.
        /// </summary>
        public static string CarRegistration {
            get {
                return ResourceManager.GetString("CarRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reset.
        /// </summary>
        public static string CarResetBtn {
            get {
                return ResourceManager.GetString("CarResetBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        public static string CarSaveBtn {
            get {
                return ResourceManager.GetString("CarSaveBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete info.
        /// </summary>
        public static string CarsDeleteInfo {
            get {
                return ResourceManager.GetString("CarsDeleteInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Details.
        /// </summary>
        public static string CarsDetails {
            get {
                return ResourceManager.GetString("CarsDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Car State.
        /// </summary>
        public static string CarState {
            get {
                return ResourceManager.GetString("CarState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid State.
        /// </summary>
        public static string CarStateError {
            get {
                return ResourceManager.GetString("CarStateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на On repair.
        /// </summary>
        public static string CarStateRepairing {
            get {
                return ResourceManager.GetString("CarStateRepairing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Working.
        /// </summary>
        public static string CarStateWorking {
            get {
                return ResourceManager.GetString("CarStateWorking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Car status.
        /// </summary>
        public static string CarStatus {
            get {
                return ResourceManager.GetString("CarStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Change status for current car?.
        /// </summary>
        public static string CarStatusConfirmation {
            get {
                return ResourceManager.GetString("CarStatusConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Status change confirmation.
        /// </summary>
        public static string CarStatusConfirmHeader {
            get {
                return ResourceManager.GetString("CarStatusConfirmHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Main.
        /// </summary>
        public static string CarStatusMain {
            get {
                return ResourceManager.GetString("CarStatusMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Spare.
        /// </summary>
        public static string CarStatusSpare {
            get {
                return ResourceManager.GetString("CarStatusSpare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Menu.
        /// </summary>
        public static string CarToMenuBtn {
            get {
                return ResourceManager.GetString("CarToMenuBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Change driver.
        /// </summary>
        public static string ChangeDriver {
            get {
                return ResourceManager.GetString("ChangeDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Change menu.
        /// </summary>
        public static string ChangeMenu {
            get {
                return ResourceManager.GetString("ChangeMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Change.
        /// </summary>
        public static string ChangeOwner {
            get {
                return ResourceManager.GetString("ChangeOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Change.
        /// </summary>
        public static string ChangeString {
            get {
                return ResourceManager.GetString("ChangeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на City districts.
        /// </summary>
        public static string Citydistricts {
            get {
                return ResourceManager.GetString("Citydistricts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Client.
        /// </summary>
        public static string Client {
            get {
                return ResourceManager.GetString("Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Drive History.
        /// </summary>
        public static string ClientDriveHistory {
            get {
                return ResourceManager.GetString("ClientDriveHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your order have been confirmed.
        /// </summary>
        public static string ClientOrderConfirm {
            get {
                return ResourceManager.GetString("ClientOrderConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Client Service.
        /// </summary>
        public static string ClientService {
            get {
                return ResourceManager.GetString("ClientService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Are you sure you want to delete this address?.
        /// </summary>
        public static string ConfirmDeletingAddress {
            get {
                return ResourceManager.GetString("ConfirmDeletingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirmed orders.
        /// </summary>
        public static string ConfirmedByDrivers {
            get {
                return ResourceManager.GetString("ConfirmedByDrivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirm request.
        /// </summary>
        public static string ConfirmRequest {
            get {
                return ResourceManager.GetString("ConfirmRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Contact Information.
        /// </summary>
        public static string ContactInformation {
            get {
                return ResourceManager.GetString("ContactInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter all required information into the form below..
        /// </summary>
        public static string CreateAttention1 {
            get {
                return ResourceManager.GetString("CreateAttention1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You need to add all information correctly..
        /// </summary>
        public static string CreateAttention2 {
            get {
                return ResourceManager.GetString("CreateAttention2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Here is car registration page.
        /// </summary>
        public static string CreateHeader1 {
            get {
                return ResourceManager.GetString("CreateHeader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Keep in mind.
        /// </summary>
        public static string CreateHeader2 {
            get {
                return ResourceManager.GetString("CreateHeader2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на We still don&apos;t know where You are. Please choose district of Your location..
        /// </summary>
        public static string CreateLocation {
            get {
                return ResourceManager.GetString("CreateLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add new address.
        /// </summary>
        public static string CreateNewAddressString {
            get {
                return ResourceManager.GetString("CreateNewAddressString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Data.
        /// </summary>
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Chernivtsi.
        /// </summary>
        public static string DefaultValueOfCity {
            get {
                return ResourceManager.GetString("DefaultValueOfCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You are attempting to delete all information about selected car. Deleted information will be lost..
        /// </summary>
        public static string DeleteAttention1 {
            get {
                return ResourceManager.GetString("DeleteAttention1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete Confirmation.
        /// </summary>
        public static string deleteConfirm {
            get {
                return ResourceManager.GetString("deleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Deleted!.
        /// </summary>
        public static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Deleted districts list.
        /// </summary>
        public static string DeletedDistricts {
            get {
                return ResourceManager.GetString("DeletedDistricts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Do you really want to delete this entry?.
        /// </summary>
        public static string deleteDstEntryQuestion {
            get {
                return ResourceManager.GetString("deleteDstEntryQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Attention!.
        /// </summary>
        public static string DeleteHeader1 {
            get {
                return ResourceManager.GetString("DeleteHeader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        public static string deleteString {
            get {
                return ResourceManager.GetString("deleteString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Demo page.
        /// </summary>
        public static string DemoPage {
            get {
                return ResourceManager.GetString("DemoPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Denied.
        /// </summary>
        public static string Denied {
            get {
                return ResourceManager.GetString("Denied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unfortunatly your orders is denied, please try again.
        /// </summary>
        public static string DeniedOrder {
            get {
                return ResourceManager.GetString("DeniedOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Denied request.
        /// </summary>
        public static string DeniedToDriver {
            get {
                return ResourceManager.GetString("DeniedToDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You can view all your car info here..
        /// </summary>
        public static string DetailsAttention1 {
            get {
                return ResourceManager.GetString("DetailsAttention1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Here is car details page.
        /// </summary>
        public static string DetailsHeader1 {
            get {
                return ResourceManager.GetString("DetailsHeader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Details.
        /// </summary>
        public static string detailsString {
            get {
                return ResourceManager.GetString("detailsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на District.
        /// </summary>
        public static string District {
            get {
                return ResourceManager.GetString("District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Basket.
        /// </summary>
        public static string DistrictBasket {
            get {
                return ResourceManager.GetString("DistrictBasket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на District editor.
        /// </summary>
        public static string DistrictEditor {
            get {
                return ResourceManager.GetString("DistrictEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на District name.
        /// </summary>
        public static string DistrictName {
            get {
                return ResourceManager.GetString("DistrictName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на District name error. Must contain from 4 to 30 cymbols (cyrillic or latin letters).
        /// </summary>
        public static string DistrictNameError {
            get {
                return ResourceManager.GetString("DistrictNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Here you can find information about other drivers currently working.
        ///					To start workingshift please press &quot;Start Shift&quot; button.
        /// </summary>
        public static string DistrictPartAttention1 {
            get {
                return ResourceManager.GetString("DistrictPartAttention1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Do not forget to end your working shift by pressing &quot;End Shift&quot; button.
        /// </summary>
        public static string DistrictPartAttention2 {
            get {
                return ResourceManager.GetString("DistrictPartAttention2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This is your working place.
        /// </summary>
        public static string DistrictPartHeader1 {
            get {
                return ResourceManager.GetString("DistrictPartHeader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Keep in mind.
        /// </summary>
        public static string DistrictPartHeader2 {
            get {
                return ResourceManager.GetString("DistrictPartHeader2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Districts.
        /// </summary>
        public static string Districts {
            get {
                return ResourceManager.GetString("Districts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Doing order.
        /// </summary>
        public static string DoingOrder {
            get {
                return ResourceManager.GetString("DoingOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Drive.
        /// </summary>
        public static string Drive {
            get {
                return ResourceManager.GetString("Drive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Driver.
        /// </summary>
        public static string Driver {
            get {
                return ResourceManager.GetString("Driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You are here.
        /// </summary>
        public static string DriverIsHere {
            get {
                return ResourceManager.GetString("DriverIsHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Driver Request.
        /// </summary>
        public static string DriverRequest {
            get {
                return ResourceManager.GetString("DriverRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Drivers.
        /// </summary>
        public static string Drivers {
            get {
                return ResourceManager.GetString("Drivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Drivers activity.
        /// </summary>
        public static string DriversActivity {
            get {
                return ResourceManager.GetString("DriversActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Drivers income.
        /// </summary>
        public static string DriversIncome {
            get {
                return ResourceManager.GetString("DriversIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Drop place.
        /// </summary>
        public static string DropPlace {
            get {
                return ResourceManager.GetString("DropPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter all required information into the form below..
        /// </summary>
        public static string EditAttention1 {
            get {
                return ResourceManager.GetString("EditAttention1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit or delete your information wisely!.
        /// </summary>
        public static string EditAttention2 {
            get {
                return ResourceManager.GetString("EditAttention2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Here is car registration page.
        /// </summary>
        public static string EditHeader1 {
            get {
                return ResourceManager.GetString("EditHeader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Be carefull.
        /// </summary>
        public static string EditHeader2 {
            get {
                return ResourceManager.GetString("EditHeader2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на If You like to change Your location,  please choose district from the list..
        /// </summary>
        public static string EditLocation {
            get {
                return ResourceManager.GetString("EditLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit.
        /// </summary>
        public static string editString {
            get {
                return ResourceManager.GetString("editString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit car info.
        /// </summary>
        public static string EditYourCar {
            get {
                return ResourceManager.GetString("EditYourCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email is empty.
        /// </summary>
        public static string EmptyEmail {
            get {
                return ResourceManager.GetString("EmptyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password is empty.
        /// </summary>
        public static string EmptyPassword {
            get {
                return ResourceManager.GetString("EmptyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на UserName is empty.
        /// </summary>
        public static string EmptyUserName {
            get {
                return ResourceManager.GetString("EmptyUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter new district name:.
        /// </summary>
        public static string enterDistrictName {
            get {
                return ResourceManager.GetString("enterDistrictName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter new district name.
        /// </summary>
        public static string enterNewDstName {
            get {
                return ResourceManager.GetString("enterNewDstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter your address.
        /// </summary>
        public static string EnterYourAdress {
            get {
                return ResourceManager.GetString("EnterYourAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на First name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fuel Consumption.
        /// </summary>
        public static string FuelConsumption {
            get {
                return ResourceManager.GetString("FuelConsumption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your garage.
        /// </summary>
        public static string Garage {
            get {
                return ResourceManager.GetString("Garage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All information about your car or cars will be displayed here. You can always view, add, edit or delete each car you want..
        /// </summary>
        public static string GarageAttention1 {
            get {
                return ResourceManager.GetString("GarageAttention1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Always keep your information up to date. Do not forget to update information you submited..
        /// </summary>
        public static string GarageAttention2 {
            get {
                return ResourceManager.GetString("GarageAttention2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This is your virtual garage.
        /// </summary>
        public static string GarageHeader1 {
            get {
                return ResourceManager.GetString("GarageHeader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Keep in mind.
        /// </summary>
        public static string GarageHeader2 {
            get {
                return ResourceManager.GetString("GarageHeader2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Giveaway confirmation.
        /// </summary>
        public static string GiveCarConfirmation {
            get {
                return ResourceManager.GetString("GiveCarConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Give this car to a new owner?.
        /// </summary>
        public static string GiveCarEntry {
            get {
                return ResourceManager.GetString("GiveCarEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Welcome home.
        /// </summary>
        public static string Greeting {
            get {
                return ResourceManager.GetString("Greeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Has order.
        /// </summary>
        public static string HasOrder {
            get {
                return ResourceManager.GetString("HasOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hello.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Income (UAH).
        /// </summary>
        public static string IncomeUAH {
            get {
                return ResourceManager.GetString("IncomeUAH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Info.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Input Your message:.
        /// </summary>
        public static string InputYourMessage {
            get {
                return ResourceManager.GetString("InputYourMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Is intersity.
        /// </summary>
        public static string IsIntercity {
            get {
                return ResourceManager.GetString("IsIntercity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Is standart.
        /// </summary>
        public static string IsStandart {
            get {
                return ResourceManager.GetString("IsStandart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Join.
        /// </summary>
        public static string Join {
            get {
                return ResourceManager.GetString("Join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Last name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Last update.
        /// </summary>
        public static string LastUpdate {
            get {
                return ResourceManager.GetString("LastUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login.
        /// </summary>
        public static string log {
            get {
                return ResourceManager.GetString("log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Log In.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на UserName or Email is already exists.
        /// </summary>
        public static string LoginEmailExist {
            get {
                return ResourceManager.GetString("LoginEmailExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Log out.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на To main menu.
        /// </summary>
        public static string MainLink {
            get {
                return ResourceManager.GetString("MainLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Map.
        /// </summary>
        public static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New message from driver.
        /// </summary>
        public static string MessageFromDriver {
            get {
                return ResourceManager.GetString("MessageFromDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New message from operator:.
        /// </summary>
        public static string MessageFromOperator {
            get {
                return ResourceManager.GetString("MessageFromOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Message has been sent!.
        /// </summary>
        public static string MessageHasBeenSent {
            get {
                return ResourceManager.GetString("MessageHasBeenSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Messages.
        /// </summary>
        public static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Message to drivers.
        /// </summary>
        public static string MessageToDrivers {
            get {
                return ResourceManager.GetString("MessageToDrivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Message to operators.
        /// </summary>
        public static string MessageToOperators {
            get {
                return ResourceManager.GetString("MessageToOperators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Middle name.
        /// </summary>
        public static string MiddleName {
            get {
                return ResourceManager.GetString("MiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Minimal price.
        /// </summary>
        public static string MinimalPrice {
            get {
                return ResourceManager.GetString("MinimalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на minutes.
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на My account.
        /// </summary>
        public static string MyAccount {
            get {
                return ResourceManager.GetString("MyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New owner.
        /// </summary>
        public static string newCarOwner {
            get {
                return ResourceManager.GetString("newCarOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New orders.
        /// </summary>
        public static string NewOrders {
            get {
                return ResourceManager.GetString("NewOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unfortunatly there is no float car right now.
        /// </summary>
        public static string NoCar {
            get {
                return ResourceManager.GetString("NoCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No status.
        /// </summary>
        public static string NoStatus {
            get {
                return ResourceManager.GetString("NoStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Number.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Number.
        /// </summary>
        public static string NumberHouse {
            get {
                return ResourceManager.GetString("NumberHouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OK.
        /// </summary>
        public static string okString {
            get {
                return ResourceManager.GetString("okString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на One minute cost.
        /// </summary>
        public static string OneMinuteCost {
            get {
                return ResourceManager.GetString("OneMinuteCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Operator.
        /// </summary>
        public static string Operator {
            get {
                return ResourceManager.GetString("Operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Order.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Diagrama of orders.
        /// </summary>
        public static string OrderDiagrama {
            get {
                return ResourceManager.GetString("OrderDiagrama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your order in progress, please wait.
        /// </summary>
        public static string OrderInProgress {
            get {
                return ResourceManager.GetString("OrderInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Orders per district.
        /// </summary>
        public static string OrdersPerDistrictStat {
            get {
                return ResourceManager.GetString("OrdersPerDistrictStat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Order Taxi.
        /// </summary>
        public static string OrderTaxi {
            get {
                return ResourceManager.GetString("OrderTaxi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OrderTime.
        /// </summary>
        public static string OrderTime {
            get {
                return ResourceManager.GetString("OrderTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Peec place.
        /// </summary>
        public static string PeekPlace {
            get {
                return ResourceManager.GetString("PeekPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Personal cabinet.
        /// </summary>
        public static string PersonalCabinet {
            get {
                return ResourceManager.GetString("PersonalCabinet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Registration.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ReportViewer.
        /// </summary>
        public static string ReportViewer {
            get {
                return ResourceManager.GetString("ReportViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The current field is empty. Please fill it..
        /// </summary>
        public static string RequiredError {
            get {
                return ResourceManager.GetString("RequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Resting.
        /// </summary>
        public static string Resting {
            get {
                return ResourceManager.GetString("Resting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Restore.
        /// </summary>
        public static string RestoreDistrict {
            get {
                return ResourceManager.GetString("RestoreDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Return.
        /// </summary>
        public static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Return this car to it`s owner?.
        /// </summary>
        public static string ReturnCarEntry {
            get {
                return ResourceManager.GetString("ReturnCarEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Return confirmation.
        /// </summary>
        public static string ReturnConfirmation {
            get {
                return ResourceManager.GetString("ReturnConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Run time.
        /// </summary>
        public static string Runtime {
            get {
                return ResourceManager.GetString("Runtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        public static string saveButton {
            get {
                return ResourceManager.GetString("saveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select Tarif.
        /// </summary>
        public static string SelectTarif {
            get {
                return ResourceManager.GetString("SelectTarif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Oops, something went wrong....
        /// </summary>
        public static string ServerErrorHeader {
            get {
                return ResourceManager.GetString("ServerErrorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sorry, something happened when your data was pocessed. But don`t worry. Everything`s okay. Please try again or contact administrator..
        /// </summary>
        public static string ServerErrorMessage {
            get {
                return ResourceManager.GetString("ServerErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Set.
        /// </summary>
        public static string Set {
            get {
                return ResourceManager.GetString("Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Set date.
        /// </summary>
        public static string Setdate {
            get {
                return ResourceManager.GetString("Setdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на VIP clients.
        /// </summary>
        public static string SetVIPStatusPage {
            get {
                return ResourceManager.GetString("SetVIPStatusPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password is less than 5 characters.
        /// </summary>
        public static string ShortPassword {
            get {
                return ResourceManager.GetString("ShortPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на UserName is less than 4 characters.
        /// </summary>
        public static string ShortUserName {
            get {
                return ResourceManager.GetString("ShortUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sing Up.
        /// </summary>
        public static string SingUp {
            get {
                return ResourceManager.GetString("SingUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start price.
        /// </summary>
        public static string StartPrice {
            get {
                return ResourceManager.GetString("StartPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reports and statistics.
        /// </summary>
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Street.
        /// </summary>
        public static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Take order.
        /// </summary>
        public static string TakeOrder {
            get {
                return ResourceManager.GetString("TakeOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tarifes.
        /// </summary>
        public static string Tarifes {
            get {
                return ResourceManager.GetString("Tarifes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Time to travel to the client (min) : .
        /// </summary>
        public static string TimeFromOrder {
            get {
                return ResourceManager.GetString("TimeFromOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add new address.
        /// </summary>
        public static string TitleCreateAddress {
            get {
                return ResourceManager.GetString("TitleCreateAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add Your location.
        /// </summary>
        public static string TitleCreateLocation {
            get {
                return ResourceManager.GetString("TitleCreateLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete current address.
        /// </summary>
        public static string TitleDeleteAddress {
            get {
                return ResourceManager.GetString("TitleDeleteAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit current address.
        /// </summary>
        public static string TitleEditAddress {
            get {
                return ResourceManager.GetString("TitleEditAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Update Your location.
        /// </summary>
        public static string TitleEditLocation {
            get {
                return ResourceManager.GetString("TitleEditLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Favourite addresses.
        /// </summary>
        public static string TitleLeftMenuUserAddress {
            get {
                return ResourceManager.GetString("TitleLeftMenuUserAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your favourite addresses.
        /// </summary>
        public static string TitleMainMenuAddress {
            get {
                return ResourceManager.GetString("TitleMainMenuAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Location.
        /// </summary>
        public static string TitleMainMenuLocation {
            get {
                return ResourceManager.GetString("TitleMainMenuLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Update profile.
        /// </summary>
        public static string UpdateProfile {
            get {
                return ResourceManager.GetString("UpdateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User Id.
        /// </summary>
        public static string UserId {
            get {
                return ResourceManager.GetString("UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User list.
        /// </summary>
        public static string UserMenu {
            get {
                return ResourceManager.GetString("UserMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User page.
        /// </summary>
        public static string UserPage {
            get {
                return ResourceManager.GetString("UserPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wait.
        /// </summary>
        public static string Wait {
            get {
                return ResourceManager.GetString("Wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Waiting cost.
        /// </summary>
        public static string WaitingCost {
            get {
                return ResourceManager.GetString("WaitingCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Waiting orders.
        /// </summary>
        public static string WaitingOrders {
            get {
                return ResourceManager.GetString("WaitingOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на WaitingTime.
        /// </summary>
        public static string WaitingTime {
            get {
                return ResourceManager.GetString("WaitingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Workshift.
        /// </summary>
        public static string WorkShift {
            get {
                return ResourceManager.GetString("WorkShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на End Shift.
        /// </summary>
        public static string WorkShiftEnd {
            get {
                return ResourceManager.GetString("WorkShiftEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start Shift.
        /// </summary>
        public static string WorkShiftStart {
            get {
                return ResourceManager.GetString("WorkShiftStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shift started.
        /// </summary>
        public static string WorkStarted {
            get {
                return ResourceManager.GetString("WorkStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your address has been deleted..
        /// </summary>
        public static string YourAddressHasBeenDeleted {
            get {
                return ResourceManager.GetString("YourAddressHasBeenDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You are in:.
        /// </summary>
        public static string YourCurrentLocation {
            get {
                return ResourceManager.GetString("YourCurrentLocation", resourceCulture);
            }
        }
    }
}
