// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CARNICKNAMEfieldincarModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CARNICKNAMEfieldincarModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201510091416110_CARNICKNAME field in car Model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
