// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class EngleshfieldaddedtoOrderExmodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EngleshfieldaddedtoOrderExmodel));
        
        string IMigrationMetadata.Id
        {
            get { return "201605251353275_Englesh-field-added-to-OrderEx-model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
